/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const ProfileLazyImport = createFileRoute('/profile')()
const LoginLazyImport = createFileRoute('/login')()
const CarsLazyImport = createFileRoute('/cars')()
const IndexLazyImport = createFileRoute('/')()
const AdminDashboardLazyImport = createFileRoute('/admin/dashboard')()
const AdminTypesCreateLazyImport = createFileRoute('/admin/types/create')()
const AdminTypesIdLazyImport = createFileRoute('/admin/types/$id')()
const AdminModelsCreateLazyImport = createFileRoute('/admin/models/create')()
const AdminModelsIdLazyImport = createFileRoute('/admin/models/$id')()
const AdminManufacturesCreateManufacturesLazyImport = createFileRoute(
  '/admin/manufactures/createManufactures',
)()
const AdminManufacturesIdLazyImport = createFileRoute(
  '/admin/manufactures/$id',
)()
const AdminCarsCreateLazyImport = createFileRoute('/admin/cars/create')()
const AdminCarsIdLazyImport = createFileRoute('/admin/cars/$id')()
const AdminTypesEditIdLazyImport = createFileRoute('/admin/types/edit/$id')()
const AdminModelsEditIdLazyImport = createFileRoute('/admin/models/edit/$id')()
const AdminManufacturesEditIdLazyImport = createFileRoute(
  '/admin/manufactures/edit/$id',
)()
const AdminCarsEditIdLazyImport = createFileRoute('/admin/cars/edit/$id')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const CarsLazyRoute = CarsLazyImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cars.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AdminDashboardLazyRoute = AdminDashboardLazyImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/dashboard.lazy').then((d) => d.Route),
)

const AdminTypesCreateLazyRoute = AdminTypesCreateLazyImport.update({
  id: '/admin/types/create',
  path: '/admin/types/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/types/create.lazy').then((d) => d.Route),
)

const AdminTypesIdLazyRoute = AdminTypesIdLazyImport.update({
  id: '/admin/types/$id',
  path: '/admin/types/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/types/$id.lazy').then((d) => d.Route),
)

const AdminModelsCreateLazyRoute = AdminModelsCreateLazyImport.update({
  id: '/admin/models/create',
  path: '/admin/models/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/models/create.lazy').then((d) => d.Route),
)

const AdminModelsIdLazyRoute = AdminModelsIdLazyImport.update({
  id: '/admin/models/$id',
  path: '/admin/models/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/models/$id.lazy').then((d) => d.Route),
)

const AdminManufacturesCreateManufacturesLazyRoute =
  AdminManufacturesCreateManufacturesLazyImport.update({
    id: '/admin/manufactures/createManufactures',
    path: '/admin/manufactures/createManufactures',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/manufactures/createManufactures.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminManufacturesIdLazyRoute = AdminManufacturesIdLazyImport.update({
  id: '/admin/manufactures/$id',
  path: '/admin/manufactures/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/manufactures/$id.lazy').then((d) => d.Route),
)

const AdminCarsCreateLazyRoute = AdminCarsCreateLazyImport.update({
  id: '/admin/cars/create',
  path: '/admin/cars/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/create.lazy').then((d) => d.Route),
)

const AdminCarsIdLazyRoute = AdminCarsIdLazyImport.update({
  id: '/admin/cars/$id',
  path: '/admin/cars/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/$id.lazy').then((d) => d.Route),
)

const AdminTypesEditIdLazyRoute = AdminTypesEditIdLazyImport.update({
  id: '/admin/types/edit/$id',
  path: '/admin/types/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/types/edit/$id.lazy').then((d) => d.Route),
)

const AdminModelsEditIdLazyRoute = AdminModelsEditIdLazyImport.update({
  id: '/admin/models/edit/$id',
  path: '/admin/models/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/models/edit/$id.lazy').then((d) => d.Route),
)

const AdminManufacturesEditIdLazyRoute =
  AdminManufacturesEditIdLazyImport.update({
    id: '/admin/manufactures/edit/$id',
    path: '/admin/manufactures/edit/$id',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/manufactures/edit/$id.lazy').then((d) => d.Route),
  )

const AdminCarsEditIdLazyRoute = AdminCarsEditIdLazyImport.update({
  id: '/admin/cars/edit/$id',
  path: '/admin/cars/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/cars/edit/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/$id': {
      id: '/admin/cars/$id'
      path: '/admin/cars/$id'
      fullPath: '/admin/cars/$id'
      preLoaderRoute: typeof AdminCarsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/create': {
      id: '/admin/cars/create'
      path: '/admin/cars/create'
      fullPath: '/admin/cars/create'
      preLoaderRoute: typeof AdminCarsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufactures/$id': {
      id: '/admin/manufactures/$id'
      path: '/admin/manufactures/$id'
      fullPath: '/admin/manufactures/$id'
      preLoaderRoute: typeof AdminManufacturesIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufactures/createManufactures': {
      id: '/admin/manufactures/createManufactures'
      path: '/admin/manufactures/createManufactures'
      fullPath: '/admin/manufactures/createManufactures'
      preLoaderRoute: typeof AdminManufacturesCreateManufacturesLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/models/$id': {
      id: '/admin/models/$id'
      path: '/admin/models/$id'
      fullPath: '/admin/models/$id'
      preLoaderRoute: typeof AdminModelsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/models/create': {
      id: '/admin/models/create'
      path: '/admin/models/create'
      fullPath: '/admin/models/create'
      preLoaderRoute: typeof AdminModelsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/types/$id': {
      id: '/admin/types/$id'
      path: '/admin/types/$id'
      fullPath: '/admin/types/$id'
      preLoaderRoute: typeof AdminTypesIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/types/create': {
      id: '/admin/types/create'
      path: '/admin/types/create'
      fullPath: '/admin/types/create'
      preLoaderRoute: typeof AdminTypesCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/cars/edit/$id': {
      id: '/admin/cars/edit/$id'
      path: '/admin/cars/edit/$id'
      fullPath: '/admin/cars/edit/$id'
      preLoaderRoute: typeof AdminCarsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/manufactures/edit/$id': {
      id: '/admin/manufactures/edit/$id'
      path: '/admin/manufactures/edit/$id'
      fullPath: '/admin/manufactures/edit/$id'
      preLoaderRoute: typeof AdminManufacturesEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/models/edit/$id': {
      id: '/admin/models/edit/$id'
      path: '/admin/models/edit/$id'
      fullPath: '/admin/models/edit/$id'
      preLoaderRoute: typeof AdminModelsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/types/edit/$id': {
      id: '/admin/types/edit/$id'
      path: '/admin/types/edit/$id'
      fullPath: '/admin/types/edit/$id'
      preLoaderRoute: typeof AdminTypesEditIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cars': typeof CarsLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/cars/$id': typeof AdminCarsIdLazyRoute
  '/admin/cars/create': typeof AdminCarsCreateLazyRoute
  '/admin/manufactures/$id': typeof AdminManufacturesIdLazyRoute
  '/admin/manufactures/createManufactures': typeof AdminManufacturesCreateManufacturesLazyRoute
  '/admin/models/$id': typeof AdminModelsIdLazyRoute
  '/admin/models/create': typeof AdminModelsCreateLazyRoute
  '/admin/types/$id': typeof AdminTypesIdLazyRoute
  '/admin/types/create': typeof AdminTypesCreateLazyRoute
  '/admin/cars/edit/$id': typeof AdminCarsEditIdLazyRoute
  '/admin/manufactures/edit/$id': typeof AdminManufacturesEditIdLazyRoute
  '/admin/models/edit/$id': typeof AdminModelsEditIdLazyRoute
  '/admin/types/edit/$id': typeof AdminTypesEditIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cars': typeof CarsLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/cars/$id': typeof AdminCarsIdLazyRoute
  '/admin/cars/create': typeof AdminCarsCreateLazyRoute
  '/admin/manufactures/$id': typeof AdminManufacturesIdLazyRoute
  '/admin/manufactures/createManufactures': typeof AdminManufacturesCreateManufacturesLazyRoute
  '/admin/models/$id': typeof AdminModelsIdLazyRoute
  '/admin/models/create': typeof AdminModelsCreateLazyRoute
  '/admin/types/$id': typeof AdminTypesIdLazyRoute
  '/admin/types/create': typeof AdminTypesCreateLazyRoute
  '/admin/cars/edit/$id': typeof AdminCarsEditIdLazyRoute
  '/admin/manufactures/edit/$id': typeof AdminManufacturesEditIdLazyRoute
  '/admin/models/edit/$id': typeof AdminModelsEditIdLazyRoute
  '/admin/types/edit/$id': typeof AdminTypesEditIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/cars': typeof CarsLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/cars/$id': typeof AdminCarsIdLazyRoute
  '/admin/cars/create': typeof AdminCarsCreateLazyRoute
  '/admin/manufactures/$id': typeof AdminManufacturesIdLazyRoute
  '/admin/manufactures/createManufactures': typeof AdminManufacturesCreateManufacturesLazyRoute
  '/admin/models/$id': typeof AdminModelsIdLazyRoute
  '/admin/models/create': typeof AdminModelsCreateLazyRoute
  '/admin/types/$id': typeof AdminTypesIdLazyRoute
  '/admin/types/create': typeof AdminTypesCreateLazyRoute
  '/admin/cars/edit/$id': typeof AdminCarsEditIdLazyRoute
  '/admin/manufactures/edit/$id': typeof AdminManufacturesEditIdLazyRoute
  '/admin/models/edit/$id': typeof AdminModelsEditIdLazyRoute
  '/admin/types/edit/$id': typeof AdminTypesEditIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/dashboard'
    | '/admin/cars/$id'
    | '/admin/cars/create'
    | '/admin/manufactures/$id'
    | '/admin/manufactures/createManufactures'
    | '/admin/models/$id'
    | '/admin/models/create'
    | '/admin/types/$id'
    | '/admin/types/create'
    | '/admin/cars/edit/$id'
    | '/admin/manufactures/edit/$id'
    | '/admin/models/edit/$id'
    | '/admin/types/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cars'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/dashboard'
    | '/admin/cars/$id'
    | '/admin/cars/create'
    | '/admin/manufactures/$id'
    | '/admin/manufactures/createManufactures'
    | '/admin/models/$id'
    | '/admin/models/create'
    | '/admin/types/$id'
    | '/admin/types/create'
    | '/admin/cars/edit/$id'
    | '/admin/manufactures/edit/$id'
    | '/admin/models/edit/$id'
    | '/admin/types/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/cars'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/dashboard'
    | '/admin/cars/$id'
    | '/admin/cars/create'
    | '/admin/manufactures/$id'
    | '/admin/manufactures/createManufactures'
    | '/admin/models/$id'
    | '/admin/models/create'
    | '/admin/types/$id'
    | '/admin/types/create'
    | '/admin/cars/edit/$id'
    | '/admin/manufactures/edit/$id'
    | '/admin/models/edit/$id'
    | '/admin/types/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CarsLazyRoute: typeof CarsLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  AdminDashboardLazyRoute: typeof AdminDashboardLazyRoute
  AdminCarsIdLazyRoute: typeof AdminCarsIdLazyRoute
  AdminCarsCreateLazyRoute: typeof AdminCarsCreateLazyRoute
  AdminManufacturesIdLazyRoute: typeof AdminManufacturesIdLazyRoute
  AdminManufacturesCreateManufacturesLazyRoute: typeof AdminManufacturesCreateManufacturesLazyRoute
  AdminModelsIdLazyRoute: typeof AdminModelsIdLazyRoute
  AdminModelsCreateLazyRoute: typeof AdminModelsCreateLazyRoute
  AdminTypesIdLazyRoute: typeof AdminTypesIdLazyRoute
  AdminTypesCreateLazyRoute: typeof AdminTypesCreateLazyRoute
  AdminCarsEditIdLazyRoute: typeof AdminCarsEditIdLazyRoute
  AdminManufacturesEditIdLazyRoute: typeof AdminManufacturesEditIdLazyRoute
  AdminModelsEditIdLazyRoute: typeof AdminModelsEditIdLazyRoute
  AdminTypesEditIdLazyRoute: typeof AdminTypesEditIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CarsLazyRoute: CarsLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  AdminDashboardLazyRoute: AdminDashboardLazyRoute,
  AdminCarsIdLazyRoute: AdminCarsIdLazyRoute,
  AdminCarsCreateLazyRoute: AdminCarsCreateLazyRoute,
  AdminManufacturesIdLazyRoute: AdminManufacturesIdLazyRoute,
  AdminManufacturesCreateManufacturesLazyRoute:
    AdminManufacturesCreateManufacturesLazyRoute,
  AdminModelsIdLazyRoute: AdminModelsIdLazyRoute,
  AdminModelsCreateLazyRoute: AdminModelsCreateLazyRoute,
  AdminTypesIdLazyRoute: AdminTypesIdLazyRoute,
  AdminTypesCreateLazyRoute: AdminTypesCreateLazyRoute,
  AdminCarsEditIdLazyRoute: AdminCarsEditIdLazyRoute,
  AdminManufacturesEditIdLazyRoute: AdminManufacturesEditIdLazyRoute,
  AdminModelsEditIdLazyRoute: AdminModelsEditIdLazyRoute,
  AdminTypesEditIdLazyRoute: AdminTypesEditIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/cars",
        "/login",
        "/profile",
        "/register",
        "/admin/dashboard",
        "/admin/cars/$id",
        "/admin/cars/create",
        "/admin/manufactures/$id",
        "/admin/manufactures/createManufactures",
        "/admin/models/$id",
        "/admin/models/create",
        "/admin/types/$id",
        "/admin/types/create",
        "/admin/cars/edit/$id",
        "/admin/manufactures/edit/$id",
        "/admin/models/edit/$id",
        "/admin/types/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/cars": {
      "filePath": "cars.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/profile": {
      "filePath": "profile.lazy.jsx"
    },
    "/register": {
      "filePath": "register.lazy.jsx"
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.lazy.jsx"
    },
    "/admin/cars/$id": {
      "filePath": "admin/cars/$id.lazy.jsx"
    },
    "/admin/cars/create": {
      "filePath": "admin/cars/create.lazy.jsx"
    },
    "/admin/manufactures/$id": {
      "filePath": "admin/manufactures/$id.lazy.jsx"
    },
    "/admin/manufactures/createManufactures": {
      "filePath": "admin/manufactures/createManufactures.lazy.jsx"
    },
    "/admin/models/$id": {
      "filePath": "admin/models/$id.lazy.jsx"
    },
    "/admin/models/create": {
      "filePath": "admin/models/create.lazy.jsx"
    },
    "/admin/types/$id": {
      "filePath": "admin/types/$id.lazy.jsx"
    },
    "/admin/types/create": {
      "filePath": "admin/types/create.lazy.jsx"
    },
    "/admin/cars/edit/$id": {
      "filePath": "admin/cars/edit/$id.lazy.jsx"
    },
    "/admin/manufactures/edit/$id": {
      "filePath": "admin/manufactures/edit/$id.lazy.jsx"
    },
    "/admin/models/edit/$id": {
      "filePath": "admin/models/edit/$id.lazy.jsx"
    },
    "/admin/types/edit/$id": {
      "filePath": "admin/types/edit/$id.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
